version: "3.9"

services:
  db:
    image: postgres:15
    container_name: quotes_db
    restart: always
    environment:
      POSTGRES_DB: quotesdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: django_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:admin123@db:5432/quotesdb

  frontend:
    build: ./quote-frontend
    container_name: react_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata: