# Generated by Django 5.2.14 on 2026-05-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Motivation', 'Motivation'), ('Success', 'Success'), ('Life', 'Life')], default='Motivation', max_length=20)),
            ],
        ),
    ]
